### ISSUE TITLE
Change required python version

### ISSUE THREAD

**Issue by taharallouche** [ruizdesotto/data_cliff#34]
### Description

In the `setup.py`, the `python_requires` is set to `>=3.6`. This, however, is not compatible with the use of `|` for the type annotations of `Union`.

### Suggested changes
- [ ] Change the required python version `>=3.10`

**Comment by ruizdesotto** [comment]
I think we should actually do the opposite @taharallouche 

We should make sure that this package works on most of the python versions

We should set up the pipeline with tox to ensure it!
